version: "3"
 
services:
  postgres:
    image: "postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
 
  api:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/party-api
      - api-gems:/api-gems
    tty: true
    stdin_open: true
 
volumes:
  postgres:
  api-gems: