default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: party-api_development

test:
  <<: *default
  database: party-api_test

production:
  <<: *default
  database: party-api_production
  username: party-api
  password: <%= ENV['PARTY-API_DATABASE_PASSWORD'] %>
