default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres

development:
  <<: *default
  database: eveenz_api_development

test:
  <<: *default
  database: eveenz_api_test

staging:
  <<: *default
  database: eveenz
  username: eveenz_api
  password: <%= ENV['EVEENZ_API_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: eveenz_api_production
  username: eveenz_api
  password: <%= ENV['EVEENZ_API_DATABASE_PASSWORD'] %>
