default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: mateusveloso

development:
  <<: *default
  database: party_api_development

test:
  <<: *default
  database: party_api_test

staging:
  <<: *default
  database: party_api_staging
  username: party_api
  password: <%= ENV['PARTY_API_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: party_api_production
  username: party_api
  password: <%= ENV['PARTY_API_DATABASE_PASSWORD'] %>
