# Settings file to all environments

# Expiration time in hours
Jwt:
  JWT_EXPIRATION_TIME: 720
  ENABLE_EXP_TIME: false

# Custom Exception Messages
Exceptions:
  UNAUTHORIZED: "unauthorized"
  USER_IS_NOT_ACTIVE: "User is not active!"

# Auth Providers
Providers:
  FACEBOOK: "facebook"
