name: Master Release

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up actions
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with RSpec
      run: |
        sudo apt-get install postgresql -y
        sudo apt-get install libpq-dev -y
        gem install bundler
        bundle install --jobs 4 --retry 3
        export RAILS_ENV=test
        bundle exec rake db:schema:load
        bundle exec rspec spec
